from .user_keyboards import (
    get_start_keyboard,
    get_language_keyboard,
    get_start_keyboard_uz,
    get_contact_keyboard,
    get_packages_keyboard,
    get_people_keyboard,
    get_lang_settings_keyboard,
)
from .admin_keyboards import (
    get_admin_main_keyboard,
    get_pending_orders_keyboard,
    get_order_view_keyboard,
    get_confirm_call_keyboard,
    get_history_keyboard,
    get_history_order_keyboard,
    get_packages_keyboard as get_admin_packages_keyboard,
    get_package_manage_keyboard,
    get_waiting_orders_keyboard,
    get_waiting_order_keyboard,
)

__all__ = [
    "get_start_keyboard",
    "get_language_keyboard",
    "get_start_keyboard_uz",
    "get_contact_keyboard",
    "get_packages_keyboard",
    "get_people_keyboard",
    "get_lang_settings_keyboard",
    "get_admin_main_keyboard",
    "get_pending_orders_keyboard",
    "get_order_view_keyboard",
    "get_confirm_call_keyboard",
    "get_history_keyboard",
    "get_history_order_keyboard",
    "get_admin_packages_keyboard",
    "get_package_manage_keyboard",
    "get_waiting_orders_keyboard",
    "get_waiting_order_keyboard",
]
