# User messages translations
USER_MESSAGES = {
    'ru': {
        'welcome_new': "Привет! Добро пожаловать в D.A.M TRAVEL AGENCY.\nВыберите язык:",
        'welcome_return': "Нажмите кнопку ниже, чтобы начать оформление заявки.",
        'start_btn': "Начать",
        'has_pending': "У вас уже есть активная заявка. Дождитесь обработки администратором.",
        'enter_name': "Введите ваше имя:",
        'enter_phone': "Введите номер телефона.\nПример: +998901234567",
        'enter_phone_btn': "📱 Поделиться контактом",
        'enter_destination': "Куда вы хотите путишествовать?\nВведите адрес или выберите пакет:",
        'enter_people': "Сколько человек поедет?\nВыберите количество:",
        'enter_time': "На сколько дней вы решили путишествовать?\nВыберите количество дней:",
        'order_accepted': "Ваша заявка принятаю Оператор свяжется с вами.",
        'lang_settings': "Выберите язык:",
        'lang_changed_ru': "Язык изменён на русский ✅",
        'lang_changed_uz': "Til o'zbekchaga o'zgartirildi ✅",
        'custom_time': "Введите количество дней:",
        'invalid_number': "Пожалуйста, введите числовое значение.",
    },
    'uz': {
        'welcome_new': "Assalomu alaykum! Bu D.A.M TRAVEL AGENCY.\nTilni tanlang:",
        'welcome_return': "Assalomu alaykum! D.A.M TRAVEL AGENCY botimizga xush kelibsz\nQuyidagi tugmani bosing va ozingizga maqul bolgan sayohatni boshlang.",
        'start_btn': "Boshlash",
        'has_pending': "Sizda allaqachon faol buyurtma mavjud. Administrator tomonidan ko'rib chiqilishini kuting.",
        'enter_name': "Ismingizni kiriting:",
        'enter_phone': "Telefon raqamingizni kiriting.\nMisol: +998901234567",
        'enter_phone_btn': "📱 Telefon raqam",
        'enter_destination': "Qayerga borasiz?\nQayerga sayohat qilmoqchisz:",
        'enter_people': "Necha odam bilan sayohat qilmoqchisz?\nSonini tanlang:",
        'enter_time': "qancha kunga sayohat rejalashtirdingiz?\nkunni tanlang tanlang:",
        'order_accepted': "Hurmatli mijoz buyurtmangiz qabul qilindi. szga tez orada operatorlarimiz bog'lanadi.",
        'lang_settings': "Tilni tanlang:",
        'lang_changed_ru': "Til ruschaga o'zgartirildi ✅",
        'lang_changed_uz': "Til o'zbekchaga o'zgartirildi ✅",
        'custom_time': "Qancha kun sayohat qilmoqchisiz:",
        'invalid_number': "Iltimos, son qiymatini kiriting.",
    }
}

# Admin panel translations
ADMIN_MESSAGES = {
    'ru': {
        'no_access': "У вас нет доступа к админ-панели.",
        'no_access_alert': "У вас нет доступа.",
        'admin_panel': "Админ-панель",
        'btn_pending': "Входящие заявки",
        'btn_waiting': "В ожидании",
        'btn_history': "История заявок",
        'btn_packages': "Добавить пакетов",
        'no_pending': "Нет активных заявок.",
        'no_waiting': "Нет заявок на рассмотрении.",
        'no_history': "История пуста.",
        'order_not_found': "Заявка не найдена.",
        'order_deleted': "Заявка #{order_id} удалена.",
        'call_question': "Вы договорились о поездке?",
        'btn_yes': "Да✅",
        'btn_no': "Нет❌",
        'btn_wait': "На рассмотрении⏳",
        'btn_back': "🔙 Назад",
        'btn_delete': "🗑 Удалить",
        'btn_add_package': "➕ Добавить пакет",
        'btn_custom': "Написать другой",
        'packages_title': "Управление пакетами:",
        'packages_empty': "Список пакетов пуст.\nНажмите ➕ Добавить пакет, чтобы создать новый.",
        'pkg_enter_name': "Введите название нового пакета:",
        'pkg_added': "Пакет '{name}' добавлен!",
        'pkg_exists': "Такой пакет уже существует!",
        'pkg_deleted': "Пакет удален.",
        'pkg_deleted_empty': "Пакет удален. Список пакетов пуст.",
        'pkg_empty_name': "Название не может быть пустым!",
        'status_accepted': "принятая",
        'status_rejected': "отклоненная",
        'status_pending_review': "на рассмотрении",
        'order_marked': "Заявка #{order_id} отмечена как {status}.",
        'page_info': "{current}/{total}:\nВсего: {total_count}",
        'btn_prev': "⬅️ Назад",
        'btn_next': "Вперед ➡️",
        'status_pending_review_display': "⏳ На рассмотрении",
        'btn_go_to': "Перейти",
        'name': "Имя",
        'phone': "Телефон",
        'destination': "Куда",
        'people_count': "Людей",
        'time': "Время",
    },
    'uz': {
        'no_access': "Sizda admin panelga kirish huquqi yo'q.",
        'no_access_alert': "Sizda kirish huquqi yo'q.",
        'admin_panel': "Admin panel",
        'btn_pending': "Kiruvchi buyurtmalar",
        'btn_waiting': "Kutishda",
        'btn_history': "Buyurtmalar tarixi",
        'btn_packages': "Paket qo'shish",
        'no_pending': "Faol buyurtmalar yo'q.",
        'no_waiting': "Ko'rib chiqilayotgan buyurtmalar yo'q.",
        'no_history': "Tarix bo'sh.",
        'order_not_found': "Buyurtma topilmadi.",
        'order_deleted': "Buyurtma #{order_id} o'chirildi.",
        'call_question': "Mijoz bilan gaplashdingizmi?",
        'btn_yes': "Ha✅",
        'btn_no': "Yo'q❌",
        'btn_wait': "Ko'rib chiqishda⏳",
        'btn_back': "🔙 Orqaga",
        'btn_delete': "🗑 O'chirish",
        'btn_add_package': "➕ Paket qo'shish",
        'btn_custom': "Boshqa yozish",
        'packages_title': "Tour paketlarni boshqarish:",
        'packages_empty': "Tour paketlar ro'yxati bo'sh.\nYangi paket yaratish uchun ➕ Paket qo'shish tugmasini bosing.",
        'pkg_enter_name': "Yangi tour paket nomini kiriting:",
        'pkg_added': "'{name}' tour paketi qo'shildi!",
        'pkg_exists': "Bunday tour paket allaqachon mavjud!",
        'pkg_deleted': "Tour paket o'chirildi.",
        'pkg_deleted_empty': "Tour paket o'chirildi. Tour paketlar ro'yxati bo'sh.",
        'pkg_empty_name': "Nomi bo'sh bo'lishi mumkin emas!",
        'status_accepted': "tasdiqlangan",
        'status_rejected': "rad etilgan",
        'status_pending_review': "ko'rib chiqilmoqda",
        'order_marked': "Buyurtma #{order_id} {status} sifatida belgilandi.",
        'page_info': "{current}/{total}:\nJami: {total_count}",
        'btn_prev': "⬅️ Orqaga",
        'btn_next': "Oldinga ➡️",
        'status_pending_review_display': "⏳ Ko'rib chiqilmoqda",
        'btn_go_to': "O'tish",
        'name': "Ism",
        'phone': "Telefon",
        'destination': "Qayerga",
        'people_count': "Kishilar soni",
        'time': "Vaqt",
    }
}

# Channel message translations
CHANNEL_MESSAGES = {
    'ru': {
        'new_order': "Новая заявка",
        'name': "Имя",
        'phone': "Телефон",
        'destination': "Куда",
        'people_count': "Количество человек",
        'time': "Время",
        'status_accepted': "✅ ПОДТВЕРЖДЕНО",
        'status_rejected': "❌ ОТКЛОНЕНО",
        'status_pending_review': "⏳ НА РАССМОТРЕНИИ",
    },
    'uz': {
        'new_order': "Yangi buyurtma",
        'name': "Ism",
        'phone': "Telefon",
        'destination': "Qayerga",
        'people_count': "Kishilar soni",
        'time': "Vaqt",
        'status_accepted': "✅ TASDIQLANDI",
        'status_rejected': "❌ RAD ETILDI",
        'status_pending_review': "⏳ KO'RIB CHIQILMOQDA",
    }
}

# Keyboard button translations
KEYBOARD_BUTTONS = {
    'ru': {
        'lang_ru': "🇷🇺 Русский",
        'lang_uz': "🇺🇿 O'zbekcha",
        'start': "Начать",
        'contact': "📱 Поделиться контактом",
        'write_address': "Ввести адрес",
        'custom_people': "Другое количество",
        'custom_time': "Своё время",
        'call_client': "Позвонил клиенту",
        'yes': "Да✅",
        'no': "Нет❌",
        'wait': "На рассмотрении⏳",
        'delete': "🗑 Удалить",
        'add_package': "➕ Добавить пакет",
        'back': "🔙 Назад",
        'pending': "Входящие заявки",
        'waiting': "В ожидании",
        'history': "История заявок",
        'packages': "Добавить пакетов",
    },
    'uz': {
        'lang_ru': "🇷🇺 Русский",
        'lang_uz': "🇺🇿 O'zbekcha",
        'start': "Boshlash",
        'contact': "📱 Telefon raqam",
        'write_address': "Manzilni yozish",
        'custom_people': "Boshqa son",
        'custom_time': "Boshqa kun",
        'call_client': "Mijozga qo'ng'iroq qildim",
        'yes': "Ha✅",
        'no': "Yo'q❌",
        'wait': "Ko'rib chiqishda⏳",
        'delete': "🗑 O'chirish",
        'add_package': "➕ Tour paket qo'shish",
        'back': "🔙 Orqaga",
        'pending': "Kiruvchi buyurtmalar",
        'waiting': "Kutishda",
        'history': "Buyurtmalar tarixi",
        'packages': "Tour paket qo'shish",
    }
}
